version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: limgwei000
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5

  fastapi_app:
    build: .
    container_name: fastapi_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST:db
      - POSTGRES_PORT:5432
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:limgwei000
      - POSTGRES_DATABASE:fastapi_db
volumes:
  postgres_data: